### ISSUE TITLE
x86_64.deb 安装后应用菜单不出现Icalingua图标

### ISSUE THREAD

**Issue by foresee-io** [Clansty/Icalingua#100]
**进展** 暂时从 https://github.com/Clansty/Icalingua/actions/runs/1092461356 下载修复权限的包。我将在下一个Release发布，且验证没有问题时关闭issue。

Bug: x86_64.deb 应用菜单不出现Icalingua图标

经检查，
`/usr/share/applications/electron-qq.desktop` 所给出的
`/opt/Icalingua/electron-qq` 没有可执行权限。
手动执行下列命令便排除故障。

`sudo chmod -R +x /opt/Icalingua`

文件的sha256
```
439bd1f7521e71eb912f7ccf12266ee14cf9d2983ddd203997d9b05b5f11ee67  ./electron-qq_2.1.3_amd64.deb
1201cb38a2d01d4801a539a482b364a0c1c049911fd4f7416151e5e29ac092ff  ./x86_64.deb.zip
```

故障类型：（很可能是）打包问题
复现：可在已更至最新的Ubuntu 20.04、Deepin 20.2.2稳定复现

**Comment by foresee-io** [comment]
从这里下载的：
https://github.com/Clansty/Icalingua/releases/tag/v2.1.3

**Comment by Clansty** [comment]
@foresee-io release 页面的下载链接已变更，请下载修复的版本

**Comment by Clansty** [comment]
@foresee-io https://github.com/Clansty/Icalingua/actions/runs/1092461356

**Comment by foresee-io** [comment]
> @foresee-io release 页面的下载链接已变更，请下载修复的版本

请待我验证一下，成功后我会自己关闭issue。麻烦了

**Comment by Jamie-obj** [comment]
![图片](https://user-images.githubusercontent.com/65389500/128117672-c4755e2b-16a3-4309-9be7-2a1630dba2f0.png)
为什么要修改软件名称呢

**Comment by lixiang810** [comment]
@Jamie-obj 因为这个软件做的已经不止QQ了

**Comment by Jamie-obj** [comment]
> @Jamie-obj 因为这个软件做的已经不止QQ了

好奇这个名字是什么意思

**Comment by Clansty** [comment]
> 好奇这个名字是什么意思

是 @91khr 想出来的

取得是「光」和「语言」的意思

**Comment by ezrameow** [comment]
@Clansty seni在群里吗
