### ISSUE TITLE
x86_64.pkg.tar.zst 安装后在应用菜单与dock栏图标均显示为默认齿轮图标

### ISSUE THREAD

**Issue by lomirus** [Clansty/Icalingua#104]
下载版本：[修复权限问题](https://github.com/Clansty/Icalingua/actions/runs/1092461356)

关于应用菜单的图标问题，经查，发现安装后在 `/usr/share/icons/hicolor/512x512/apps` 会出现 `icalingua.png` ，而在 `/usr/share/applications/icalingua.desktop` 中的内容却为:
```
[Desktop Entry]
Categories=chat;Network;
Exec=electron-qq %u
Icon=electron-qq.png
Name=Electron QQ
Comment=A cross-platform QQ made with Electron
Terminal=false
Type=Application
```
将其中的 `Icon` 修改为对应路径后可修复应用菜单的图标问题，不过 dock 栏的图标问题目前还没解决。

例图：
![example](https://z3.ax1x.com/2021/08/05/fVJWdA.png)

**Comment by lomirus** [comment]
另外再提一下托盘图标显示的是 Electron 的默认图标

**Comment by lixiang810** [comment]
建议从 https://aur.archlinux.org/packages/electron-qq/ clone 下 pkg，然后替换 app.asar 进去updpkgsum && makepkg，然后再 pacman -U 应该就正常了。
原因在于作者改了软件名，但细节没搞好

**Comment by lixiang810** [comment]
（顺便求个图标包名

**Comment by lomirus** [comment]
> （顺便求个图标包名

@lixiang810 `Papirus-Dark-Maia`, Manjaro Gnome 自带的

**Comment by Clansty** [comment]
已修复
