### ISSUE TITLE
[Feature Request] 表情功能增强

### ISSUE THREAD

**Issue by alex3236** [Clansty/Icalingua#107]
## 功能需求
1. 支持官方 QQ 表情的发送
2. 文字联想表情简写（`/xxx`或`:xx:`，与官方表情对应，也可增加自定义和修改支持）

## 供参考
[啧.tk](https://xn--9zr.tk/) - 收录了 QQ 所有表情以及简写
[CQHTTP文档-表情码](https://github.com/kyubotics/coolq-http-api/wiki/%E8%A1%A8%E6%83%85-CQ-%E7%A0%81-ID-%E8%A1%A8) - 可视化的 QQ 表情以及对应的表情码（

**Comment by lixiang810** [comment]
这个强啊

**Comment by lixiang810** [comment]
不过， 啧.tk 上面的表情是啥格式的呢

**Comment by eagle3236** [comment]
> 不过， 啧.tk 上面的表情是啥格式的呢

PNG格式

**Comment by eagle3236** [comment]
更新：
理论上只需要发送 `[Face: ID]` 即可发送原版表情 :)

**Comment by Clansty** [comment]
@eagle3236 不行，因为我使用消息链发送消息，相当于是转义了

**Comment by eagle3236** [comment]
> @eagle3236 不行，因为我使用消息链发送消息，相当于是转义了

那能不能作为图片表情发送？
