### ISSUE TITLE
[BUG] 2.1.4 版本 Dock 栏及托盘图标仍然存在问题

### ISSUE THREAD

**Issue by lomirus** [Clansty/Icalingua#120]
## Describe the bug / 描述
之前反馈过一次 [Arch 系的图标问题](https://github.com/Clansty/Icalingua/issues/104)，包括启动菜单和 Dock 的图标均显示异常。现在那个 issue 已经被关闭，我安装了新版之后发现启动菜单的图标问题确实被修复了，不过 Dock 栏依旧显示异常。而且鼠标悬浮的提示信息是 `electron-qq`，估计原因和上次差不多。

## To Reproduce / 复现过程

```bash
sudo pacman -U icalingua-2.1.4-1-x86_64.pkg.tar.zst
```

## Expected behavior / 预期的结果

显示为 Icalingua 图标

## Screenshots / 截图

- Dock 图标
![Dock](https://s3.bmp.ovh/imgs/2021/08/2b0d067cf3108a60.png)

- 托盘图标
![](https://s3.bmp.ovh/imgs/2021/08/ffaa75d84b95b264.png)

## System informations / 系统信息

 - OS: Manjaro
 - Version: 2.1.4

**Comment by kands-code** [comment]
唔，2.1.5版，appimage的任务栏图标还是有问题，显示为x server图标
![图片](https://user-images.githubusercontent.com/59006329/129433337-6d6dfd53-4959-4ed6-9db6-d6e91b977dc1.png)
