### ISSUE TITLE
[BUG]部分表情包太占地了

### ISSUE THREAD

**Issue by foresee-io** [Clansty/Icalingua#121]
**To Reproduce / 复现过程**
0. 登录Icalingua (QQ)
1. 在最新的手机QQ发送内置的 菜汪 表情
2. 在Icalingua查看消息，问题复现

**Expected behavior / 预期的结果**
调整布局，让此类图片与聊天框看起来更和谐

**Screenshots / 截图**
1. 手Q
![0](https://user-images.githubusercontent.com/32860378/128619311-59935e91-d2ba-45a6-8a46-1a90d96d803c.jpeg)

2. Icalingua
![image](https://user-images.githubusercontent.com/32860378/128621020-78a539fd-b846-439d-809a-3e97d7558a00.png)

**System informations / 系统信息**
 - OS: Ubuntu 20.04.2
 - Version 2.1.4

**Comment by foresee-io** [comment]
第一版issue不慎泄露了一点隐私，现已编辑issue并删除历史记录

**Comment by foresee-io** [comment]
第二版移除原因同理

**Comment by Jamie-obj** [comment]
还有一个问题就是每次打开图片都是全屏打开，太占地方，可以开一个小窗口就可以了

**Comment by Ptestq** [comment]
可以增加本地查看器开关,如果会话图片都在同目录的话连看也解决了

**Comment by rain15z3** [comment]
> 还有一个问题就是每次打开图片都是全屏打开，太占地方，可以开一个小窗口就可以了

收到

**Comment by CoelacanthusHex** [comment]
@rain15z3 其实 telegram 也是全屏打开的

**Comment by Clansty** [comment]
@CoelacanthusHex 我就是学的 telegram

**Comment by Clansty** [comment]
不过如果能判断图片大小来调整窗口的话也不错，但是感觉涉及到的 IPC 操作有点多

**Comment by Clansty** [comment]
在有独立图片查看器之前我用的是 el-image 自带的查看器，会在主窗口中模态显示，我觉得不好，就改成了现在这样子。当时那个也是全屏的

**Comment by Clansty** [comment]
> 可以增加本地查看器开关,如果会话图片都在同目录的话连看也解决了

是支持用本地查看器打开的，但是图片文件并不落在本地，原理是用本地查看器打开网络图片。现在会话窗口中看见的图片也是用 `<img src="...">` 加载的网络图片

**Comment by rain15z3** [comment]
> @CoelacanthusHex 我就是学的 telegram

我发现不用全屏，也能根据图片尺寸大小打开。

**Comment by Clansty** [comment]
@rain15z3 好诶

**Comment by Jamie-obj** [comment]
还有一个问题，当右键点击右下角图标修改优先级时，双图标问题还会复现
@Clansty

**Comment by Clansty** [comment]
啊这 这是 DDE 的锅吧qwq

（上游的修复还不到位（x

**Comment by CoelacanthusHex** [comment]
> 啊这 这是 DDE 的锅吧qwq
> 
> （上游的修复还不到位（x

这不是最生草的，最生草的是 Deepin 官方更了新版但是要过很久 DDE 的仓库才打 tag（
