### ISSUE TITLE
[BUG]给自己发消息时……

### ISSUE THREAD

**Issue by foresee-io** [Clansty/Icalingua#122]
**To Reproduce / 复现过程**
0. 登录Icalingua (QQ)
1. 在Friends列表找到自己，进入对话
2. 随便给自己发消息
3. _问题复现，刚发的消息出现了2次。官方客户端没这问题_

**Expected behavior / 预期的结果**
给自己发的消息，在聊天框只应出现1次

**Screenshots / 截图**
![Screen210808-122455](https://user-images.githubusercontent.com/32860378/128620741-b742fa39-d16a-4b6d-ae9a-ab3282af8941.png)

**System informations / 系统信息**
 - OS: Ubuntu 20.04
 - Version [2.1.4]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Clansty** [comment]
不应该给自己发消息

**Comment by lixiang810** [comment]
@Clansty 草

**Comment by ezrameow** [comment]
@lixiang810 fix: 删除了打开自己聊天窗口的功能

**Comment by Clansty** [comment]
@ezrameow 对我正准备这么干！

**Comment by Clansty** [comment]
@Clansty 以前也有人提过这个问题，我一直没有把这个功能关掉。原版没有和自己聊天的功能

**Comment by foresee-io** [comment]
> 
> 
> @Clansty 以前也有人提过这个问题，我一直没有把这个功能关掉。原版没有和自己聊天的功能

实际上原版QQ有和自己聊天的功能，调出步骤同上。

主要用在多平台间传文件。一次传输，同步到**所有**终端。

当然**不准备修bug也没关系**，毕竟是做的非官方版本。

**Comment by Clansty** [comment]
@foresee-io 建议建一个群。如果为了方便传输文件还可以开启自动下载聊天文件功能
