### ISSUE TITLE
[BUG] 在点击重新加载后出现无法加载个人信息

### ISSUE THREAD

**Issue by CharlieYu4994** [Clansty/Icalingua#123]
**Describe the bug / 描述**
在点击重新加载后出现无法加载个人信息
1. 头像显示为 QQ 企鹅图标
2. QQ 号为 0
3. 发送的消息虽然显示名称是 You 但出现在左侧

**To Reproduce / 复现过程**
点击顶部菜单栏中的重新加载，然后问题出现

**Expected behavior / 预期的结果**
正常重新加载

**Screenshots / 截图**
![Screenshot_20210809_103950](https://user-images.githubusercontent.com/29250409/128655289-8ee91c8d-6731-43f5-ae12-d7d764bd35bc.png)
![Screenshot_20210809_104147](https://user-images.githubusercontent.com/29250409/128655373-8f7c8bb7-3042-4baa-944e-af73a0683eeb.png)

**System informations / 系统信息**
 - OS: Manjaro Linux
 - Version: 2.1.4

**Comment by Clansty** [comment]
Duplicate of #99
