### ISSUE TITLE
[BUG]无法加载好友、群组以及会话列表

### ISSUE THREAD

**Issue by jkfx** [Clansty/Icalingua#126]
**Describe the bug / 描述**

登录上去之后是空白的，历史的消息会话列表没有，偶尔有一两个群消息蹦出来；

好友列表是空，群组列表也是；

**To Reproduce / 复现过程**

正常登录，数据库选择 SQL lite 这样，之后选择 mysql （版本8.0）也这样

**Expected behavior / 预期的结果**

加载出最近的会话列表以及历史消息？

加载出好友列表、群组列表、屏蔽的群列表

**Screenshots / 截图**

![1](http://tva2.sinaimg.cn/large/006VTcCxly1gtbooc1uv0j61ig0zegok02.jpg)

![2](https://tvax3.sinaimg.cn/large/006VTcCxly1gtboososmnj61i60z40vi02.jpg)

![3](http://tva2.sinaimg.cn/large/006VTcCxly1gtbop2vtrnj61i60zadjn02.jpg)

![4](http://tva4.sinaimg.cn/large/006VTcCxly1gtbopaqrxoj61i60zch3402.jpg)

**System informations / 系统信息**

 - OS: Ubuntu x64
 - Version 20.04

**Additional context / 附加信息**

看到开发者选项有报错，是 `getFriendsAndGroups` 这个函数调用的问题？还是我本地环境问题导致的。

```
renderer.js:62 加载完成
electron/js2c/renderer_init.js:73 Uncaught (in promise) Error: Error invoking remote method 'getFriendsAndGroups': TypeError: Cannot read property 'friends' of undefined
    at EventEmitter.i.invoke (electron/js2c/renderer_init.js:73)
i.invoke @ electron/js2c/renderer_init.js:73
Promise.then (async)
created @ renderer.js:62
Ge @ renderer.js:7
ii @ renderer.js:7
e._init @ renderer.js:7
a @ renderer.js:7
(anonymous) @ renderer.js:7
init @ renderer.js:7
(anonymous) @ renderer.js:7
d @ renderer.js:7
f @ renderer.js:7
d @ renderer.js:7
(anonymous) @ renderer.js:7
e._update @ renderer.js:7
n @ renderer.js:7
fi.get @ renderer.js:7
fi @ renderer.js:7
(anonymous) @ renderer.js:7
Si.$mount @ renderer.js:7
Si.$mount @ renderer.js:7
init @ renderer.js:7
(anonymous) @ renderer.js:7
d @ renderer.js:7
f @ renderer.js:7
d @ renderer.js:7
(anonymous) @ renderer.js:7
e._update @ renderer.js:7
n @ renderer.js:7
fi.get @ renderer.js:7
fi @ renderer.js:7
(anonymous) @ renderer.js:7
Si.$mount @ renderer.js:7
Si.$mount @ renderer.js:7
init @ renderer.js:7
(anonymous) @ renderer.js:7
d @ renderer.js:7
(anonymous) @ renderer.js:7
C @ renderer.js:7
(anonymous) @ renderer.js:7
e._update @ renderer.js:7
n @ renderer.js:7
fi.get @ renderer.js:7
fi.run @ renderer.js:7
hi @ renderer.js:7
(anonymous) @ renderer.js:7
Qe @ renderer.js:7
Promise.then (async)
Ke @ renderer.js:7
rt @ renderer.js:7
(anonymous) @ renderer.js:7
fi.update @ renderer.js:7
he.notify @ renderer.js:7
set @ renderer.js:7
mi.set @ renderer.js:7
click @ renderer.js:62
Ge @ renderer.js:7
i @ renderer.js:7
Ge @ renderer.js:7
e.$emit @ renderer.js:7
click @ renderer.js:62
Ge @ renderer.js:7
i @ renderer.js:7
Qn.o._wrapper @ renderer.js:7
Show 16 more frames
```

**Comment by Clansty** [comment]
@lixiang810 似乎也遇到过这个问题，我觉得是 QQ 空间那个取好友接口引起的。我可以加个备用的取好友列表方法来解决这个问题

**Comment by jkfx** [comment]
> @lixiang810 似乎也遇到过这个问题，我觉得是 QQ 空间那个取好友接口引起的。我可以加个备用的取好友列表方法来解决这个问题

感谢修复，坐等更新

**Comment by lixiang810** [comment]
> 是 `getFriendsAndGroups` 这个函数调用的问题？还是我本地环境问题导致的

不是。getFriends应该是在main进程里的，不会在renderer里的console里报错。你这一段应该是renderer里的vue没收到main发来的信息导致的。

**Comment by jkfx** [comment]
> > 是 `getFriendsAndGroups` 这个函数调用的问题？还是我本地环境问题导致的
> 
> 不是。getFriends应该是在main进程里的，不会在renderer里的console里报错。你这一段应该是renderer里的vue没收到main发来的信息导致的。

如何才能修复，完全不懂前端= =

**Comment by lixiang810** [comment]
@jkfx 我也没法排bug，并且我现在也一直获取不到好友列表。
介绍一下electron吧：main进程可以视为一个node.js后端，renderer进程可以视为一个浏览器，里面跑前端的js代码。
但在我的使用过程中，这两者均没有有意义的报错，可以预见排错会是相当困难的事情

**Comment by lixiang810** [comment]
@Clansty 不是说在下一个 release 前先不删 bug 这个 label 吗

**Comment by Clansty** [comment]
@lixiang810 不是啊，我说的是不 close issue，用户看到 open 的 issue 就不会再开新的 issue 了
