### ISSUE TITLE
[BUG] 最新 AUR 版本托盤圖標損壞

### ISSUE THREAD

**Issue by narisuzu** [Clansty/Icalingua#131]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
AUR 2.1.4-3 版本托盤圖標爲 electron 缺省圖標.

**To Reproduce / 复现过程**
`[AUR helper] -S icalingua`

**Expected behavior / 预期的结果**
正確顯示托盤圖標

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![image](https://user-images.githubusercontent.com/16162768/128975376-e9813060-dbcc-4eeb-a0cf-5de96d86cbb3.png)

**System informations / 系统信息**
Arch Linux; Build ID: rolling

**Comment by Clansty** [comment]
在最新的 AUR 2.1.4-4 中已修复

**Comment by Clansty** [comment]
@narisuzu 啊这，忘改 sha 了

**Comment by Clansty** [comment]
@Clansty 已修复

**Comment by narisuzu** [comment]
![image](https://user-images.githubusercontent.com/16162768/128982376-c4a66a79-c755-45a7-a961-99e5c5eb406d.png)
還是一樣的問題，tray icon 爲 electron 缺省

**Comment by CoelacanthusHex** [comment]
> ![image](https://user-images.githubusercontent.com/16162768/128982376-c4a66a79-c755-45a7-a961-99e5c5eb406d.png)
> 還是一樣的問題，tray icon 爲 electron 缺省

请说明你的桌面环境，KDE 未复现此问题

**Comment by narisuzu** [comment]
Gnome with [this extension](https://extensions.gnome.org/extension/615/appindicator-support/)

**Comment by kands-code** [comment]
> 请说明你的桌面环境，KDE 未复现此问题

2.1.5新版，archlinux，kde环境，appimage版本，任务栏图标为x server样式
![图片](https://user-images.githubusercontent.com/59006329/129433505-c97c54ac-b106-43cf-b610-b77c4e45f7d6.png)
