### ISSUE TITLE
[BUG]回复状态在切换会话后会继续保留

### ISSUE THREAD

**Issue by Xeonacid** [Clansty/Icalingua#141]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
回复状态在切换会话后会继续保留

**To Reproduce / 复现过程**
- 右键点一条消息的回复
- 切换会话
- 回复状态依然还在（发送会附带回复状态，但是不会显示）

**Expected behavior / 预期的结果**
回复状态消失

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![2021-08-13_18-09](https://user-images.githubusercontent.com/13995937/129341596-92f33e77-b22c-4d50-956f-041b155b2806.png)

**System informations / 系统信息**
 - OS: Manjaro KDE
 - Version 2.1.5

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Clansty** [comment]
@Xeonacid （（这是故意的，你可以跨会话回复消息
