### ISSUE TITLE
[BUG]托盘图标文字显示为 electron

### ISSUE THREAD

**Issue by Xeonacid** [Clansty/Icalingua#144]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
托盘图标文字显示为 electron

**To Reproduce / 复现过程**
鼠标置于托盘图标上

**Expected behavior / 预期的结果**
显示 Icalingua

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![2021-08-13_18-09](https://user-images.githubusercontent.com/13995937/129356254-4b804845-a970-4c81-a3f8-8ada240c8495.png)

**System informations / 系统信息**
 - OS: Manjaro KDE
 - Version 2.1.5
 
**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by Clansty** [comment]
我觉得是因为用了 Arch 系统 Electron 的原因

**Comment by Xeonacid** [comment]
> 我觉得是因为用了 Arch 系统 Electron 的原因

这个也会有影响嘛，不懂电子（

**Comment by lixiang810** [comment]
@Xeonacid 应该会，因为我的keybase在托盘也显示electron

**Comment by timothyqiu** [comment]
相关上游 Issue: https://github.com/electron/electron/issues/28956
