### ISSUE TITLE
[BUG] 联系人头像更换后不会自动更新

### ISSUE THREAD

**Issue by inpachi18** [Clansty/Icalingua#146]
联系人头像更换后不会自动更新

联系人头像更换后在软件内显示如图，为更换前的头像
![image](https://user-images.githubusercontent.com/60968460/129440343-0d7501d1-bda4-4b13-8f73-f7c630e7367c.png)
查看头像功能显示的也是老头像

实际上期望的头像应该是
![image](https://user-images.githubusercontent.com/60968460/129440438-1e3eff55-baab-4a3b-8a3c-b53438b32bae.png)

**System informations / 系统信息**
 - OS: Arch Linux

**Comment by rain15z3** [comment]
选择菜单上的重新加载应该可以解决问题

**Comment by Clansty** [comment]
@rain15z3 不会的，需要：打开开发者工具，进入网络选项卡，产生请求之后随便右键一个，清除浏览器缓存，然后再重新加载

**Comment by Clansty** [comment]
@rain15z3 后续应该能加入启动时或者手动重新加载时自动清理缓存的功能

**Comment by rain15z3** [comment]
@Clansty 已添加
