### ISSUE TITLE
[BUG] 某个群始终无法发送中文消息

### ISSUE THREAD

**Issue by livrth** [Clansty/Icalingua#147]
System:Ubuntu20.04 LTS

软件版本：2.1.5

对于某个特定的群，所有中文消息发送后始终报错，如下图所示, 重新加载也还是无法发送

发送英文消息不会报错

![image](https://user-images.githubusercontent.com/45538642/129440485-954c8119-87bc-4b92-be28-ddfb7dd3c917.png)

**Comment by Clansty** [comment]
这应该是 oicq 的 bug 导致的，可以尝试用手机把电脑踢下线，或者删除 `~/.config/icalingua/data` 目录后重新登录

**Comment by livrth** [comment]
> 这应该是 oicq 的 bug 导致的，可以尝试用手机把电脑踢下线，或者删除 `~/.config/icalingua/data` 目录后重新登录

删除 data 目录后重新登录解决，thanks.
