### ISSUE TITLE
[BUG] 聊天输入框消失

### ISSUE THREAD

**Issue by Jamie-obj** [Clansty/Icalingua#149]
打开自己账号的聊天框发现，没有聊天输入框，但是Ctrl+v 回车能够把消息发出去

**Comment by Clansty** [comment]
@Jamie-obj 草 怎么还在尝试给自己发消息 看来还是禁的不彻底

**Comment by Jamie-obj** [comment]
> @Jamie-obj 草 怎么还在尝试给自己发消息 看来还是禁的不彻底

啊，自己可以加自己为好友，可以传一些文字图片等消息，还是有n亿点点方便的

**Comment by Clansty** [comment]
@Jamie-obj 建个群吧

**Comment by Jamie-obj** [comment]
> @Jamie-obj 建个群吧

还有一个功能建议是给表情列表加一个esc快捷键退出功能，
还有一个是搜索框搜索如果各个分组没有展开，搜索结果只能显示数字
![2021-08-15_14-53](https://user-images.githubusercontent.com/65389500/129469857-922c6353-93f3-4eef-881a-87733b54f4c2.png)
