### ISSUE TITLE
[BUG]debian bullseye 安装依赖问题

### ISSUE THREAD

**Issue by happyeggchen** [Clansty/Icalingua#162]
**Describe the bug / 描述**
包libappindicator3-1 在 buster中存在，在bullseye中不存在
**To Reproduce / 复现过程**
aptitude卸载在buster安装的electron-qq（它同时自动卸载虚包），再次安装最新的2.1.5版本
**Expected behavior / 预期的结果**
依赖与bullseye一致
**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/38799701/129519276-e804a632-d7a6-4417-9ac7-964ce0e6abf8.png)
**System informations / 系统信息**
 - OS: Debian
 - Version 11 bullseye

**Additional context / 附加信息**
无

**Comment by Clansty** [comment]
这应该是 [Electron builder](https://github.com/electron-userland/electron-builder) 没有及时更新导致的，参考：
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1975
https://github.com/inspectdev/inspect-issues/issues/91

**Comment by Clansty** [comment]
上游信息：https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037

**Comment by happyeggchen** [comment]
解决方案
```
wget http://ftp.us.debian.org/debian/pool/main/libi/libindicator/libindicator3-7_0.5.0-4_amd64.deb
wget http://ftp.us.debian.org/debian/pool/main/liba/libappindicator/libappindicator3-1_0.4.92-7_amd64.deb
sudo apt install ./libindicator3-7_0.5.0-4_amd64.deb
sudo apt install ./libappindicator3-1_0.4.92-7_amd64.deb
```
先装上就再说
这样就能暂时安装成功不漏东西了

**Comment by happyeggchen** [comment]
我觉得。。暂时可以关闭这个问题了呢

**Comment by fraesco123** [comment]
This is working to me in DEBIAN 11
