### ISSUE TITLE
[BUG] icalingua不能发送带有非常规的后缀名的文件

### ISSUE THREAD

**Issue by NO-MEANINGS** [Clansty/Icalingua#167]
**Describe the bug / 描述**
icalingua不能发送带有非常规的后缀名的文件

**To Reproduce / 复现过程**
取任意一文件，将其后缀名改为随机字符串（或者直接去掉），发送这个文件。可以看到发送内容变成了内容为文件名的字符串。
（另：将一个不是图片的文件的后缀名改成图片文件的后缀名，再发送，会报错；将一个不是音频的文件改成音频文件的后缀名可以发送，具体情况见截图）

**Expected behavior / 预期的结果**
正常发送这个文件

**Screenshots / 截图**
![image](https://user-images.githubusercontent.com/52484447/129547776-fdfb8166-c24d-414a-8cf9-3aac49fa4406.png)

**System informations / 系统信息**
 - OS: opensuse tw
 - Version 20210810

**Additional context / 附加信息**

**Comment by CoelacanthusHex** [comment]
Can you write title, please?

**Comment by NO-MEANINGS** [comment]
> Can you write title, please?

oh sorry i forgot it XD
