### ISSUE TITLE
[BUG] deb: 请求打包过程中添加”破坏“与”取代“关系，以平滑升级

### ISSUE THREAD

**Issue by foresee-io** [Clansty/Icalingua#172]
**进展** 我已手动卸载 `electron-qq`，避免产生该 bug。如果开发者有额外精力，不妨采纳该建议。

**Expected behavior / 预期的结果**
添加 `Breaks` 与 `Replaces` 关系，使得 `dpkg` 能够自动地卸载掉原有 `electron-qq` 而安装 `icalingua`。
参考链接：https://www.debian.org/doc/debian-policy/ch-relationships.html#overwriting-files-and-replacing-packages-replaces

**To Reproduce / 复现过程**
在已安装 `electron-qq` 的基础上直接安装 `icalingua`，得到下列错误。
```
正在解压 icalingua (2.2.0) ...
dpkg: 处理归档 $HOME/Downloads/icalingua_2.2.0_amd64.deb (--unpack)时出错：
 正试图覆盖 /opt/Icalingua/chrome_100_percent.pak，它同时被包含于软件包 electron-qq 2.1.4
dpkg-deb: 错误: 粘贴 子进程被信号(断开的管道) 终止了
在处理时有错误发生：
 $HOME/Downloads/icalingua_2.2.0_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by foresee-io** [comment]
只是稍微提出这个现象，加不加关系可能还要权衡一下

**Comment by CoelacanthusHex** [comment]
我印象里现在的 Deb 包是自动打的，大概需要有人学一下怎么搞
