### ISSUE TITLE
[Feature Request] 平滑迁移聊天数据，从 electron-qq 到 icalingua

### ISSUE THREAD

**Issue by foresee-io** [Clansty/Icalingua#173]
**Is your feature request related to a problem? Please describe.**
从 electron-qq 到 icalingua 的迁移还不够平滑，除打包问题外，还有数据迁移与删除问题。
检查发现，用户需要重新登录 Icalingua (QQ)，并且 `$HOME/.config/electron-qq` 文件夹与 `$HOME/.config/icalingua` 共存。

**Describe the solution you'd like**
针对 `electron-qq` 老用户自动地迁移数据，并删除原有 `$HOME/.config/electron-qq`。

**Comment by CoelacanthusHex** [comment]
现在应该是数据被迁移了，只是没有删除旧数据
