### ISSUE TITLE
[BUG] 文本内链接之后如果出现中文括号或导致之后的内容也被识别为超链接内容

### ISSUE THREAD

**Issue by aimerneige** [Clansty/Icalingua#176]
**Describe the bug / 描述**
文本内链接之后如果出现中文括号或导致之后的内容也被识别为超链接。如图:

![image](https://user-images.githubusercontent.com/51701792/129997221-1721639f-0b54-40b0-bfaa-7334d5460a86.png)

**To Reproduce / 复现过程**

发送或接受的消息文本中链接后紧跟中文括号`（`，之后的内容也会被识别为超链接内容

![image](https://user-images.githubusercontent.com/51701792/129997529-e27969ee-068b-4428-a3ef-9ba4e3b14a2e.png)

**Expected behavior / 预期的结果**

中文括号后相关内容不被识别为超链接

**Screenshots / 截图**

上附

**System informations / 系统信息**
 - OS: Fedora 34 (Workstation Edition) x86_64
 - Version 2.2.0

**Additional context / 附加信息**

无

**Comment by ezrameow** [comment]
@aimerneige 其实真的可能会有这种URL...

**Comment by CoelacanthusHex** [comment]
@ezrameow 比如 Arch wiki

**Comment by CoelacanthusHex** [comment]
@aimerneige 链接前后加空格是好习惯

**Comment by aimerneige** [comment]
好像还真是这样。。。

**Comment by aimerneige** [comment]
但是一般这种url一般不应该转码吗。

**Comment by aimerneige** [comment]
1. `https://github.com/Clansty/Icalingua/（）`
2. `https://github.com/Clansty/Icalingua/%EF%BC%88%EF%BC%89`

我认为 1例 的 url 应该是交给浏览器来处理的，浏览器应该能对用户的输入自动转码处理。

而聊天软件应该只识别 2例 的 url，因为从浏览器复制 url 的时候浏览器会自动编码为 2例 的 url 而不是 1例 的 url，平时分享的url更常见的是 2例 经过编码的 url，1例 的 url 通常需要手动输入而不会由浏览器复制得来。

何况发 url 不加空格的人大有人在，你可以约束自己却管不了别人。~~傻逼太多没办法 QAQ~~

**Comment by CoelacanthusHex** [comment]
@aimerneige 我个人意见还是自己加空格
 
> 何况复制 URL 不转码的工具大有人在，你可以约束自己却管不了别人。~~傻逼太多没办法 QAQ~~

**Comment by aimerneige** [comment]
但是 `http://世界一流大学.com` 这样的链接也没有解析啊
