### ISSUE TITLE
[BUG] 转发的消息 (forwarded messages) 为空

### ISSUE THREAD

**Issue by foresee-io** [Clansty/Icalingua#189]
Update: 纯文字消息不触发 bug，但若转发内容包含文件、图片就会出问题

**Describe the bug / 描述**
我们使用官方QQ的”合并转发消息“功能以免消息淹没。
在Icalingua (QQ)中，它会在聊天框以下列形式呈现：
![图片](https://user-images.githubusercontent.com/32860378/130717181-2c9b56e0-4990-4c3f-ac5c-fa1d36fb8857.png)
-+-+-+-+-+-分界线
但点击打开后，将显示一片空白，长久等待、重启 Icalingua 也没用。
![图片](https://user-images.githubusercontent.com/32860378/130717278-6bd1bf62-b588-448f-9781-55075432c46c.png)
-+-+-+-+-+-分界线

**To Reproduce / 复现过程**
先在官方手机QQ中找一个群，长按消息，进入”多选“模式。选择一些消息后，点击底部转发图标，选择”合并转发“，发出去。
然后在 Icalingua (QQ) 中查看它。

**System informations / 系统信息**
 - OS: Ubuntu 20.04.2
 - Version 2.2.0

**Comment by Clansty** [comment]
是必现吗，还是只有特定的消息这样

**Comment by foresee-io** [comment]
@Clansty 这里给一个例子，不妨实践一下
![图片](https://user-images.githubusercontent.com/32860378/131767772-0f3f4a3f-0f7b-43d0-b30d-e357d05b7ed0.png)


> 是必现吗，还是只有特定的消息这样

**Comment by Clansty** [comment]
如果转发消息里面没有敏感内容的话 能提供转发记录的 ResId 嘛

右键转发消息点复制代码贴上来也可以

**Comment by foresee-io** [comment]
> 如果转发消息里面没有敏感内容的话 能提供转发记录的 ResId 嘛
> 
> 右键转发消息点复制代码贴上来也可以

## 消息夹杂了文件
（等很久都不会显示出来）
```xml
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="35" templateID="1" action="viewMultiMsg" brief="[聊天记录]" m_resid="qluNsa4swP2+c70UwxKOKUihRzAVKeMdFxsV/dKY7FCr7jVY06U78+vwUKITmYPO" m_fileName="7003160020222376219" tSum="2" sourceMsgId="0" url="" flag="3" adverSign="0" multiMsgFlag="0"><item layout="1" advertiser_id="0" aid="0"><title size="34" maxLines="2" lineSpace="12">翼的聊天记录</title><title size="26" color="#777777" maxLines="2" lineSpace="12">翼:  [文件]arbitrary_file.txt</title><title size="26" color="#777777" maxLines="2" lineSpace="12">翼:  夹杂任意文件，都将出现bug</title><hr hidden="false" style="0" /><summary size="26" color="#777777">查看2条转发消息</summary></item><source name="聊天记录" icon="" action="" appid="-1" /></msg>
```
消息ID `FM6nkAAAhEomkue+YTA48AE=`

## 消息夹杂了图片
（显示正常，没有bug）
```xml
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="35" templateID="1" action="viewMultiMsg" brief="[聊天记录]" m_resid="rlENcbFir1qkiCqGYhLHIcE+674c9qZNMwxkUJz0n9RuECvljILXiCsF6aiyyhTr" m_fileName="7003162128797565301" tSum="2" sourceMsgId="0" url="" flag="3" adverSign="0" multiMsgFlag="0"><item layout="1" advertiser_id="0" aid="0"><title size="34" maxLines="2" lineSpace="12">翼的聊天记录</title><title size="26" color="#777777" maxLines="2" lineSpace="12">翼:  [图片]</title><title size="26" color="#777777" maxLines="2" lineSpace="12">翼:  只夹杂图片，不会出现bug</title><hr hidden="false" style="0" /><summary size="26" color="#777777">查看2条转发消息</summary></item><source name="聊天记录" icon="" action="" appid="-1" /></msg>
```
消息ID `FM6nkAAAhIxad0n9YTA62wE=`

**Comment by foresee-io** [comment]
非常感谢！更到2.3.0版后，问题得到了确实解决
