### ISSUE TITLE
[BUG] 屏蔽群消息后无法取消屏蔽，且没有任何标识

### ISSUE THREAD

**Issue by kands-code** [Clansty/Icalingua#190]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

我无意中点到了屏蔽群消息，然后我发现我在群里发消息，无法显示，但是手机上可以显示，而且也无法接收到消息，最主要的是这个屏蔽还没办法取消，只能删除数据库后重新加载来恢复

**To Reproduce / 复现过程**

点击屏蔽消息

![图片](https://user-images.githubusercontent.com/59006329/130726457-e8b50bf4-82e1-4ed6-9b6b-78107abb72d6.png)

**Expected behavior / 预期的结果**

点击屏蔽消息后，原来的“屏蔽消息”选项应变成“取消屏蔽”

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System informations / 系统信息**
 - OS: [e.g. Arch Linux] Arch Linux
 - Version [e.g. 2.1.4] 2.2.1 dev版

**Comment by Clansty** [comment]
@kands-code 在选项菜单里有个屏蔽会话管理

**Comment by kands-code** [comment]
诶？才发现，是我自己的问题，抱歉打扰了
