### ISSUE TITLE
[BUG] 聊天界面好友名称显示错误

### ISSUE THREAD

**Issue by MeotBot233** [Clansty/Icalingua#193]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug
应该显示好友名的位置显示了自己的名字

**To Reproduce / 复现过程**
使用其它设备给不在icalingua消息列表中的联系人发消息

**Expected behavior / 预期的结果**
正确显示好友的备注/昵称

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
没图床懒得附截图了🤣

**System information / 系统信息**
 - OS:  Arch Linux
 - Version 2.2.0

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里
初步推测是oicq获取到的消息sender是自己，导致名字显示成了自己

**Comment by lixiang810** [comment]
图可以直接拖到评论框里插入，不需要图床。

**Comment by rainbowbedrock** [comment]
> 图可以直接拖到评论框里插入，不需要图床。

欸还能直接拖的嘛没试过欸

**Comment by rainbowbedrock** [comment]
已提交PR #195
