### ISSUE TITLE
[BUG] 在macOS上菜单栏图标大小不正常

### ISSUE THREAD

**Issue by mzdluo123** [Clansty/Icalingua#196]
**Describe the bug / 描述**
在macOS上菜单栏图标大小不正常
**To Reproduce / 复现过程**
打开应用并登陆
**Expected behavior / 预期的结果**
正常显示图标大小
**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图
![image](https://user-images.githubusercontent.com/23146087/131213639-ce224a1c-129b-4a78-978a-14ae51e0ea63.png)

![image](https://user-images.githubusercontent.com/23146087/131213698-97f8bb2d-32a5-45a0-8986-c032db295362.png)

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]
macOS 11.5.2
版本 自编译2.2.0

**Additional context / 附加信息**

**Comment by Clansty** [comment]
unsupported

**Comment by lixiang810** [comment]
本 repo 只对 qq 官方支持极差的 linux 提供支持，其他系统需要自行编译，若无自行 d8g 能力，请 use it as is。
