### ISSUE TITLE
[BUG] 禁言的日期变成 1970

### ISSUE THREAD

**Issue by Clansty** [Clansty/Icalingua#201]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

禁言日期为 1970 年，排序正常

**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

**System information / 系统信息**
 - OS: [e.g. Arch Linux]
 - Version [e.g. 2.1.4]

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

**Comment by lixiang810** [comment]
Unix时间戳和JAVA时间戳的问题，前者*1000=后者。
前者是秒数，后者是毫秒。

**Comment by Clansty** [comment]
@lixiang810 是的，我忘记乘 1000 了
