### ISSUE TITLE
增加Sponsor及支持地址

### ISSUE THREAD

**Issue by Michael1015198808** [Clansty/Icalingua#205]
您好，您的项目对于广大Linux用户来说意义非常重大，我希望能够为您打赏，所以希望README中能增加打赏地址以及Sponsor栏~

**Comment by Clansty** [comment]
暂时没有接受 Sponsor 的打算

**Comment by Michael1015198808** [comment]
好滴，再次感谢您及其他贡献者的无私付出！

**Comment by lixiang810** [comment]
@Michael1015198808 要是开放 sponsor 了，就更可能被起诉了。法条有不少都是针对盈利行为的。这毕竟是个随时可能被封杀乃至起诉的项目，还请且用且珍惜。
我们的项目也基于 oicq 这个上游项目（也在 github 上），谢意也给他们一份吧。
