### ISSUE TITLE
[Feature Request] 添加加密聊天的功能

### ISSUE THREAD

**Issue by plutonemhikari** [Clansty/Icalingua#220]
**Is your feature request related to a problem? Please describe.**

让腾讯无法监控聊天内容

**Describe the solution you'd like**

使用例如gpg等成熟的加密方法，密钥由双方事先通过其他渠道交换，icalingua客户端本身只负责加密解密。实际上目前也可以完全手动完成，把密文发送出去，但是如果能够把这个功能整合进客户端会很方便。

**Describe alternatives you've considered**

**Additional context**

**Comment by lixiang810** [comment]
@plutonemhikari 现在以还原qq功能为主。加入此类功能会增加我们面临的风险，以及步其它第三方客户端后尘的概率。

**Comment by Clansty** [comment]
@lixiang810 我觉得 GPG 倒是真可以做，主要只是消息太长的问题

**Comment by Clansty** [comment]
暂时不会添加此功能

以后可能将开发插件系统，到时候可自行添加
