### ISSUE TITLE
主题问题

### ISSUE THREAD

**Issue by Do1e** [Clansty/Icalingua#222]
浅色主题下，左边依然是灰色的，希望能修改一下。
![image](https://user-images.githubusercontent.com/73533898/132292540-7da8d98f-72d1-4631-ada9-e7b7e0d91c3c.png)

**Comment by Clansty** [comment]
@Do1e 左边本来就是灰色的，从 1.0 开始就是灰色的

**Comment by Clansty** [comment]
你有没有发现深色模式左边更黑一点

**Comment by Do1e** [comment]
@Clansty 个人感觉用浅色会更加美观一点啦，抱歉之前没弄清楚。

**Comment by Clansty** [comment]
试过，不美观
