### ISSUE TITLE
[Feature Request] 避免使用存在歧义的dd/MM/yyyy日期格式

### ISSUE THREAD

**Issue by liangent** [Clansty/Icalingua#223]
**Is your feature request related to a problem? Please describe.**
目前的硬编码的dd/MM/yyyy日期格式在使用MM/dd/yyyy日期格式的地区容易被误读

**Describe the solution you'd like**
把日期格式（好像只有oicqAdapter.ts中的）改成不存在歧义的yyyy-MM-dd

**Describe alternatives you've considered**
改用Intl.DateTimeFormat()，但毕竟整个项目完全没有i18n/L10n……

**Additional context**
我试图自己下手改了，但发现有点多，所以动手之前讨论一下

**Comment by CoelacanthusHex** [comment]
@liangent ISO8601 yyds！
