### ISSUE TITLE
[Feature Request] Release 包含 Windows 版本 (

### ISSUE THREAD

**Issue by iceBear67** [Clansty/Icalingua#231]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
希望在 Release 时包含 Windows 的可分发版本  
~~自己构建构建不出来~~

**Describe alternatives you've considered**
构建教程

**Comment by Clansty** [comment]
@iceBear67 没有的

**Comment by lixiang810** [comment]
@iceBear67 icalingua的定位是解决linux用户的qq使用问题，弥补官方qq的不足。我们不敢，也无意和官方的完全版（区别于linux上的“复古版”）qq形成竞争关系

**Comment by iceBear67** [comment]
好吧

**Comment by takayama-lily** [comment]
自己偷偷编译
