### ISSUE TITLE
[BUG]在点击启动后任务栏图标过一会消失，程序也没有启动

### ISSUE THREAD

**Issue by MemoryShadow** [Clansty/Icalingua#235]
**Describe the bug / 描述**
在点击启动后任务栏图标过一会消失，程序也没有启动

**To Reproduce / 复现过程**
在我的计算机中可以必然复现，但是其他人的机器上完好。同时，在本机上使用同样由electron开发的VSCode正常

**Expected behavior / 预期的结果**
正常启动此应用

**System information / 系统信息**
 - OS: [Manjaro Linux]
 - Version [5.13.19-2-MANJARO(AMD64)]

**Additional context / 附加信息**
这个问题是我今天冷启动后注意到的，昨天最后一次启动它时，遇到了“暂时无法发送文件”的问题，然后今天这个程序就打不开了

**Comment by MemoryShadow** [comment]
此状况在重启系统后恢复正常，尚未了解是什么缘由，是否可以在wiki中新增自助指南便于自助排错呢？

**Comment by Clansty** [comment]
@MemoryShadow 你可以在终端里面运行然后看看有什么输出嘛

**Comment by MemoryShadow** [comment]
我在终端中运行了，没有任何输出，即便带上了%u参数

**Comment by MemoryShadow** [comment]
我目前正在努力复现昨天的现场，引发这个问题

**Comment by Clansty** [comment]
那应该是更新了系统核心组件没有重启导致的

在 Arch 系系统上常见这个问题，但是无影响

**Comment by MemoryShadow** [comment]
好的，谢谢
