### ISSUE TITLE
[BUG] WM下收不到通知

### ISSUE THREAD

**Issue by lygamac** [Clansty/Icalingua#237]
**Describe the bug / 描述**
使用xfce4可以收到消息通知，i3wm无通知

**To Reproduce / 复现过程**
不使用DE启动X

**Expected behavior / 预期的结果**
与DE一样，应当收到通知

**Screenshots / 截图**
~~截个寂寞~~

**System information / 系统信息**
 - OS: Arch Linux 5.14.7
 - Version 2.2.3-1

**Additional context / 附加信息**

- 与通知daemon无关，xfce4用dunst也可以收到通知
- 已满足[freedesktop-notifications](https://github.com/cronvel/freedesktop-notifications)的要求（DBUS启动，并支持org.freedesktop.Notifications）
  - Electron原生的通知我试了没问题，这个库我没用过不知道是不是这个库的问题

**Comment by happi0** [comment]
我的环境是dwm, 拥有相同的问题

**Comment by Clansty** [comment]
@happi0 awesome 好像没有问题的样子，awesome 有自己处理通知的东西

**Comment by happi0** [comment]
> @happi0 awesome 好像没有问题的样子，awesome 有自己处理通知的东西

嗯呐, 但我想dwm可能相比要困难一点 ,因为我的是自己编译的, 我的环境是dwm+st

**Comment by CoelacanthusHex** [comment]
你用 freedesktop-notification 这个库写个 MWE 测试下，如果还没通知就到上游报bug吧

**Comment by lygamac** [comment]
不止用freedesktop-notification这个库会出问题，用它基于的dbus-native直接写的通知也无效。

似乎是nodejs的bug，在wm下它要求的`NODE_MODULE_VERSION`是98，而最新的是93。de下倒是不会报这个错

```
...
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 98. Please try re-compiling or re-installing
```

**Comment by Clansty** [comment]
@lygamac 是 electron 的版本问题吧

**Comment by lygamac** [comment]
> @lygamac 是 electron 的版本问题吧

用的`15.0.0`，是要用`14.0.0`吗？

**Comment by lygamac** [comment]
electron 14.0.0要求89，也不行

**Comment by lygamac** [comment]
[Electron是通过重编译解决版本问题的](https://www.electronjs.org/docs/tutorial/using-native-node-modules#using-native-node-modules)，但是不知道为什么在wm下版本还是原来的

**Comment by Clansty** [comment]
请问你是什么系统

**Comment by lygamac** [comment]
Arch

**Comment by Clansty** [comment]
> Arch

我大概知道了，因为系统的 Electron 版本不统一

你可以试试最新的测试版本（在 Actions 中下载）那是适配 Electron 15 的版本

**Comment by lygamac** [comment]
试了，还是那样。前几天还是`14.0.1`的时候就这样了，应该不是版本不一的问题

可能是Electron对wm的支持不好吧，我去那边报个bug看看好了（因为de没任何报错wm却有）
