### ISSUE TITLE
[BUG] 无法加载好友列表

### ISSUE THREAD

**Issue by Sciroccogti** [Clansty/Icalingua#238]
**Describe the bug / 描述**
好友列表和群列表为空

**Screenshots / 截图**
![图片](https://user-images.githubusercontent.com/32357397/135186276-bac40bb9-cef8-4ca9-8c88-76c63f6da72b.png)

**System information / 系统信息**
 - OS: Ubuntu 21.04
 - Version: 2.2.3

**Additional context / 附加信息**
开发者工具没有报错

**Comment by Sciroccogti** [comment]
刷新后没有效果，也没有报错。

**Comment by Sciroccogti** [comment]
好像关闭系统代理以后可以刷新了（

**Comment by Sciroccogti** [comment]
莫名其妙好了。

**Comment by Clansty** [comment]
@Sciroccogti 可能是 cookies 获取相关的问题
