### ISSUE TITLE
登陆后未读消息不自动加载,手动加载历史记录消息框消息会串

### ISSUE THREAD

**Issue by Ptestq** [Clansty/Icalingua#31]
未读消息不标记也不会显示在通讯录中,新消息也不会即时显示
ubuntu 21.04
版本:1.5.0
storage engine: indexed DB

**Comment by Clansty** [comment]
未读消息本来就无法自动加载

历史记录的问题是乱序嘛

另外历史消息在加载的过程中不要切换到别的回话，这是 bug

**Comment by Clansty** [comment]
消息串了貌似是切换聊天窗口过快导致反应不过来

我感觉切出去再切回来可能会好吧

**Comment by halo-shit** [comment]
加载聊天记录的时候锁定聊天会话(建议

從我的 iPhone 傳送

**Comment by Clansty** [comment]
> 加载聊天记录的时候锁定聊天会话(建议

现在已经解决了加载聊天记录不能切换窗口的问题了
