### ISSUE TITLE
消息撤回（delete）后切换到其他回话返回时，仍显示原消息

### ISSUE THREAD

**Issue by ForkKILLET** [Clansty/Icalingua#42]

**Comment by kands-code** [comment]
我也遇到了同样的问题，我开始还以为是存储方式的问题，尝试了mariadb、postgresql、sqlite，以及之前的indexdb，无一例外都出现了这种情况

**Comment by lixiang810** [comment]
但我们没做撤回功能啊

**Comment by Clansty** [comment]
@lixiang810 做了

**Comment by kands-code** [comment]
> 但我们没做撤回功能啊

![图片](https://user-images.githubusercontent.com/59006329/128486118-1112b540-715c-4546-882c-e3587cf80dcb.png)

的确是有这个功能选项的，在撤回当时说有效果的，但是一旦去到别的聊天界面后再返回，被撤回的消息又会出现，尝试再次撤回会出现这个报错

![图片](https://user-images.githubusercontent.com/59006329/128486383-bc85a0b4-75d8-438e-bc2d-1036ee6ab699.png)

**Comment by lixiang810** [comment]
> 我开始还以为是存储方式的问题

不用怀疑了，就是存储的问题。而你提到的这几个数据库都有一个共同点，那就是在实现方法上使用了类 SQL 的办法。SQL的 column 是按照代码里的 type 来定义的，但 type 并没有定义全，从而导致 SQL 的 column 也没有定义全，从而产生了这个问题。
血压已经炸了。正在修复。

**Comment by kands-code** [comment]
谢谢！

**Comment by lixiang810** [comment]
已修复。待 Actions 构建完毕后可在 https://github.com/Clansty/Icalingua/actions/runs/1104696219 下载不含该 BUG 的第一个版本。
