### ISSUE TITLE
DDE 环境下托盘有两个图标

### ISSUE THREAD

**Issue by Hibanaw** [Clansty/Icalingua#68]
![image](https://user-images.githubusercontent.com/61813396/126069175-91a1e25c-6b99-4add-876b-94ee9a462723.png)

**Comment by CoelacanthusHex** [comment]
我怀疑是dde的锅……

**Comment by Clansty** [comment]
对的，早有了，我也不知道什么原因，很奇怪

**Comment by Clansty** [comment]
https://github.com/listen1/listen1_desktop/issues/324
https://bbs.deepin.org/post/196290
https://bbs.deepin.org/post/217001

Deepin 桌面下所有 electron 软件全部中招，是 DDE 的问题，等待修复

**Comment by CoelacanthusHex** [comment]
好家伙，没搜到 DDE 上游有 issue

**Comment by sukanka** [comment]
用 `bwrap` 屏蔽 `libappindicator` 应该可行,建议卸载 `libappindicator` 一劳永逸(bushi)
参考 https://bbs.deepin.org/zh/post/218404,

**Comment by CoelacanthusHex** [comment]
https://github.com/linuxdeepin/dde-dock/issues/142

**Comment by Hibanaw** [comment]
好像上游已经修复这个问题了
![image](https://user-images.githubusercontent.com/61813396/128677290-6692f58b-e855-4c1b-9be1-e21ef8b0fe15.png)
