### ISSUE TITLE
点击登录会弹出几十个KIO错误框

### ISSUE THREAD

**Issue by kudoxu** [Clansty/Icalingua#78]
![176856755](https://user-images.githubusercontent.com/23714155/127257620-24d8ca83-d799-42c7-b772-04475d46b049.jpg)

**Comment by sukanka** [comment]
版本: 2.1.0-1

点击`查看精华消息` `查看群公告` `群荣誉` 也会弹出这样的 KIO 错误框,不过只会弹一个,这些功能也正常.
![image](https://user-images.githubusercontent.com/31362108/127333840-83dd4a7b-80c5-480b-8c67-803ea1c96418.png)

**Comment by Clansty** [comment]
已修复
