### ISSUE TITLE
使用QQ邮箱登录

### ISSUE THREAD

**Issue by NO-MEANINGS** [Clansty/Icalingua#79]
在v2.1中使用qq邮箱登录时会报错：
![image](https://user-images.githubusercontent.com/52484447/127421978-0cce8631-ff68-4244-a800-388a8aa61c06.png)
随后页面卡死：
![image](https://user-images.githubusercontent.com/52484447/127422327-aa3edc78-1967-4690-81a4-1b863d3e2fae.png)

建议实现使用邮箱登录的功能。
如果难以实现，建议加一个判断分支，当用户试图使用邮箱登录时提示使用qq号而不是报错。

**Comment by Clansty** [comment]
已修复
