### ISSUE TITLE
新的dev版本使用sqlite无法抓群历史纪录

### ISSUE THREAD

**Issue by happyeggchen** [Clansty/Icalingua#82]
我拿终端开了一下，它一直抓去聊天记录，没有限制，但是如果是刚刚加好友，才说了几句话的能成功抓取，群会一直抓好像

**Comment by Clansty** [comment]
在 2.1.1 中已经修复了这个问题，可以下载测试

不过如果是新加的群没有消息记录保存，会抓取到不能再抓取为止

**Comment by happyeggchen** [comment]
还是有=.=，现在就在2.1.1-dev上，但是mongodb没这个问题

**Comment by lixiang810** [comment]
获取记录时是每获取20条抽1条来比对，确认是否已获取到旧消息。如果你旧消息不够多的话，有概率不会被抽到。

**Comment by happyeggchen** [comment]
是说electron-qq是要先有目前的历史纪录然后获取历史消息才能成功吗

**Comment by Clansty** [comment]
不是的，获取消息的机制是这样的：

从最新或者你右键的那条开始，每次往上获取 20 条消息，如果获取到的第一条在本地存在就结束，不存在就再获取 20 条

**Comment by happyeggchen** [comment]
],
  status: 'ok',
  error: null
}

我发现有一条是这样的，可是它没有说成功啥的就是一直继续加载

**Comment by Clansty** [comment]
@happyeggchen 这应该是别的什么模块输出的

**Comment by happyeggchen** [comment]
[我现在确定了有旧消息可是还是获取不了历史纪录。。。。
![image](https://user-images.githubusercontent.com/38799701/127505636-75fc95c3-ff1d-443e-93c4-9d0bb5e1a0cc.png)

**Comment by lixiang810** [comment]
等我想办法复现一下吧，我自己的版本没有这个问题。

**Comment by happyeggchen** [comment]
好像只有一个群这样，应该是我自己的问题

**Comment by happyeggchen** [comment]
现在正常了，虽然不知道为什么

**Comment by lixiang810** [comment]
不对劲，可以的话试试把那个群的聊天信息给我看看

**Comment by lixiang810** [comment]
啊这……

**Comment by lixiang810** [comment]
成功复现。只要群内有人艾特了你或者全体成员就会出问题。正在修复。

**Comment by lixiang810** [comment]
已修复。https://github.com/Clansty/Icalingua/commit/035e28f3dc3be12b8204055f2799e85f8081def5
