### ISSUE TITLE
获取历史消息时展现更多反馈

### ISSUE THREAD

**Issue by lixiang810** [Clansty/Icalingua#87]
现在获取历史消息时，只有获取完了才会提示获取了多少条信息，而在获取过程中缺乏足够的向用户反馈的机制（除了命令行输出），这样不符合某种设计原则。  
希望能在获取的同时看到一个实时增加的数字，或者一个伪进度条（比如手机网页加载那样的）。

**Comment by Clansty** [comment]
fixed
