### ISSUE TITLE
为获取历史消息增加“中止”按钮

### ISSUE THREAD

**Issue by lixiang810** [Clansty/Icalingua#92]
位置可以放在获取消息的条那里。
一个可行的方法是，添加一个默认值为false的变量，当按钮被点击时，变量值改为true，获取消息的循环中，每次循环都会检验一遍该值，若为true即停止获取，将已获取到的历史消息存入数据库。
理由：很多时候，用户并不需要获取太多历史消息，尤其是群消息较少时，若无中止按钮，则消息可能获取到很久以前，等待时间也很长。

**Comment by ezrameow** [comment]
@lixiang810 每次获取100条 翻到头了给个按钮 点一下再来100条

**Comment by Clansty** [comment]
@ezrameow 不好，不够自动化，我希望能把所有的记录都保存本地，因为其实获取一次之后会全部保存数据库但只会加载当前已加载的数量+20条

**Comment by lixiang810** [comment]
> @lixiang810 每次获取100条 翻到头了给个按钮 点一下再来100条

你的方案仅适用于聊天记录连续的情况，而实际使用中，eqq 里的聊天记录很可能是不连续的，因为eqq只有在运行时才能接收消息，不在运行时的消息会被错过。而“获取历史消息”其实也有使消息连续化的功能：它可以获取消息，直到发现新获取的消息已经在数据库里面为止。

**Comment by Jamie-obj** [comment]
![图片](https://user-images.githubusercontent.com/65389500/127963552-a593b849-3635-403b-8ddc-2112c1ee5cbc.png)
这获取历史消息是不是有点太夸张了

**Comment by lixiang810** [comment]
> 
> 
> ![图片](https://user-images.githubusercontent.com/65389500/127963552-a593b849-3635-403b-8ddc-2112c1ee5cbc.png)
> 这获取历史消息是不是有点太夸张了

如果还没有历史消息的话，很可能会获取到几千几万条为止，这也是我开这个 issue 的原因。

**Comment by sukanka** [comment]
添加一个最大获取的条数？

**Comment by lixiang810** [comment]
> 
> 
> 添加一个最大获取的条数？

写死代码不好，还是用停止按钮让用户决定获取到什么地方为止比较好

**Comment by Clansty** [comment]
@lixiang810 可以先获取指定条数并显示，然后在后台获取剩余的

**Comment by sukanka** [comment]
> 写死代码不好，还是用停止按钮让用户决定获取到什么地方为止比较好
让用户设定这个数值不就好了，加个默认值

**Comment by lixiang810** [comment]
> 让用户设定这个数值不就好了，加个默认值
那就要做设置页面了，更麻烦

**Comment by Jamie-obj** [comment]
> @lixiang810 可以先获取指定条数并显示，然后在后台获取剩余的

我最终获取了3万+消息。。。

**Comment by lixiang810** [comment]
> 我最终获取了3万+消息。。。而且还在继续获取

正常，我测试的时候获取过六万多条。

**Comment by sukanka** [comment]
@lixiang810 配置文件也可以啊，各种默认值写在里面，如果app里有个地方可以打开配置文件就更好了

**Comment by Clansty** [comment]
@sukanka 可以，现在配置文件是 yaml 格式

**Comment by lixiang810** [comment]
但我还是觉得我这个方案更好，因为不同的群需要获取的信息数量不同，有的群可能需要多获取一些，另一些群需要少获取一些，而且每次获取时用户希望获取的量都不同，用一个配置项解决仍然不满足上述需求

**Comment by Clansty** [comment]
@lixiang810 我的想法是无论如何都获取到底，但是先获取一部分展示出来

**Comment by lixiang810** [comment]
这个选择权应该交给用户，或者再增加一个获取实时进度的按钮（虽然会涉及很多处改动）

**Comment by Jamie-obj** [comment]
> @lixiang810 我的想法是无论如何都获取到底，但是先获取一部分展示出来

可以每点击一次获取100条或1000条，两个选择，用户可以点击多次，每点击一次就向上获取

**Comment by lixiang810** [comment]
本着 “talk is cheap, show me the code” 的原则，已经 commit（https://github.com/Clansty/Icalingua/commit/34298603ce28b01d29015f76fe99f0704f55c172 ）。接下来还要为 bridge 加入相应的处理机制。

**Comment by Clansty** [comment]
@Jamie-obj 不好，不够智能

**Comment by Jamie-obj** [comment]
> @Jamie-obj 不好，不够智能

参考一下钉钉，或者就先获取一部分展示在界面中，后面的部分后台获取不要展示在用户界面。另一种方案是以时间线进行获取，太久的记录一般用户不会去看，如果用户要看，让手动点击获取相应时间长度的聊天记录

**Comment by Clansty** [comment]
@Jamie-obj 只有新用户才考虑获取历史记录的问题。我除非是新加的人或者群历史记录是翻不到头的。就算是新加的群也就点一下让它后台自动获取历史

**Comment by lixiang810** [comment]
我已经整完了，欢迎继续讨论消息获取的合理机制，也可以构建一份 dev 版体验我增加的功能。
（理论上这是我第一次写 vue 代码，可喜可贺可喜可贺

**Comment by lixiang810** [comment]
> 只有新用户才考虑获取历史记录的问题

不，也有我这种不把eqq挂后台的用户

**Comment by Clansty** [comment]
> 不，也有我这种不把eqq挂后台的用户

可以考虑 bridge，可放树莓派

**Comment by lixiang810** [comment]
不是觉得占资源，是觉得没必要。我所有即时通讯软件都会杀后台，确保我随时能断开和网络的联系。历史记录嘛，反正存下来了我基本也不会看，没必要占着存储空间。对我来说获取几十条保证前后文连贯性就够了

**Comment by Jamie-obj** [comment]
> @Jamie-obj 只有新用户才考虑获取历史记录的问题。我除非是新加的人或者群历史记录是翻不到头的。就算是新加的群也就点一下让它后台自动获取历史

但是目前情况是，聊天记录它一直在获取，并没有展示，不知道是不是个例

**Comment by lixiang810** [comment]
> 聊天记录它一直在获取，并没有展示

按现在的设计就是这样的，直到获取到头为止。我刚刚的commit以后，你就可以手动停止获取了

**Comment by Jamie-obj** [comment]
> > 聊天记录它一直在获取，并没有展示
> 
> 按现在的设计就是这样的，直到获取到头为止。我刚刚的commit以后，你就可以手动停止获取了

手动停止可以，我并不需要那么多条的聊天记录，那如果想要继续获取，是从断点开始吗？

**Comment by lixiang810** [comment]
> 那如果想要继续获取，是从断点开始吗？

看你是在哪里点的获取历史消息。如果是右键一条消息点的，就是从这条消息开始，否则就是从最新的一条开始。现在应该是不会从断点开始的，因为没法保证断点后消息的连续性（比如，如果你退出后台，那么断点之后也会有消息需要获取）
