### ISSUE TITLE
建议增加Esc退出软件界面功能

### ISSUE THREAD

**Issue by Jamie-obj** [Clansty/Icalingua#94]
退出界面只能通过点击操作，不是很方便

**Comment by Clansty** [comment]
@Jamie-obj ESC 目前是关闭当前会话，Ctrl + w 是关闭界面

**Comment by Jamie-obj** [comment]
> @Jamie-obj ESC 目前是关闭当前会话，Ctrl + w 是关闭界面

在deepin下为何按ESC无任何反应，Ctrl+w是关闭界面

**Comment by Clansty** [comment]
@Jamie-obj 可以尝试更新到 2.x 版本

**Comment by Jamie-obj** [comment]
> @Jamie-obj 可以尝试更新到 2.x 版本

好的

**Comment by sukanka** [comment]
建议增加 alt+f4 退出软件，有个设置面板设置快捷键就好了。(其实我觉得这种通讯软件一般都是一直开着，有点击关闭按钮足够了)

**Comment by Clansty** [comment]
@sukanka alt+f4 是系统自带的关闭按键，是关闭到托盘的

**Comment by Jamie-obj** [comment]
> @Jamie-obj 可以尝试更新到 2.x 版本

2.1.3有问题，在deepin上安装，启动器里没有图标，桌面有，但是双击没用，打不开

**Comment by Clansty** [comment]
@Jamie-obj 那是一个打包的 bug，需要 sudo chmod +x /opt/Icalingua/electron-qq

**Comment by Jamie-obj** [comment]
> @Jamie-obj 那是一个打包的 bug，需要
> 
> ```shell
> sudo chmod +x /opt/Icalingua/electron-qq
> ```

没有启动图标诶

**Comment by Clansty** [comment]
@Jamie-obj 我待会儿来看一下 deb 包有什么问题

**Comment by Jamie-obj** [comment]
> @Jamie-obj 我待会儿来看一下 deb 包有什么问题

![图片](https://user-images.githubusercontent.com/65389500/127961394-5fd5db96-8d1d-4cbe-a2e8-2100e1b50523.png)
Mac登陆使用MongDB，Mysql, Postgresql会提示这个窗口，无法使用；
使用Redis storage engine, 
![图片](https://user-images.githubusercontent.com/65389500/127961723-3ce5f6da-286a-4ae3-a1a0-83efa706383e.png)
这里三个键粘一块儿了；
只有使用内置Storage是正常的。
还有请教一下，是如何让electron应用在dde dock下只显示一个图标呢

**Comment by CoelacanthusHex** [comment]
> 还有请教一下，是如何让electron应用在dde dock下只显示一个图标呢

https://github.com/Clansty/Icalingua/issues/68#issuecomment-891533310

**Comment by CoelacanthusHex** [comment]
> @Jamie-obj 我待会儿来看一下 deb 包有什么问题

`lintian` 一下试试？

**Comment by Jamie-obj** [comment]
> > @Jamie-obj 我待会儿来看一下 deb 包有什么问题
> 
> @Clansty `lintian` 一下试试？

emmm，我发现是改软件名字了

**Comment by Clansty** [comment]
> ![图片](https://user-images.githubusercontent.com/65389500/127961394-5fd5db96-8d1d-4cbe-a2e8-2100e1b50523.png)
> Mac登陆使用MongDB，Mysql, Postgresql会提示这个窗口，无法使用；
> 使用Redis storage engine,
> ![图片](https://user-images.githubusercontent.com/65389500/127961723-3ce5f6da-286a-4ae3-a1a0-83efa706383e.png)
> 这里三个键粘一块儿了；
> 只有使用内置Storage是正常的。
> 还有请教一下，是如何让electron应用在dde dock下只显示一个图标呢

你应该是没有启动数据库服务端或者没有正确配置连接参数。如果菜单栏没有正常加载那是软件还没加载完

**Comment by Jamie-obj** [comment]
> > ![图片](https://user-images.githubusercontent.com/65389500/127961394-5fd5db96-8d1d-4cbe-a2e8-2100e1b50523.png)
> > Mac登陆使用MongDB，Mysql, Postgresql会提示这个窗口，无法使用；
> > 使用Redis storage engine,
> > ![图片](https://user-images.githubusercontent.com/65389500/127961723-3ce5f6da-286a-4ae3-a1a0-83efa706383e.png)
> > 这里三个键粘一块儿了；
> > 只有使用内置Storage是正常的。
> > 还有请教一下，是如何让electron应用在dde dock下只显示一个图标呢
> 
> 你应该是没有启动数据库服务端或者没有正确配置连接参数。如果菜单栏没有正常加载那是软件还没加载完

请问右下角这个小图标可不可以点一下就弹出软件界面，目前操作是得右键点一下这个图标再点击打开才能启动软件界面，不是很方便
![图片](https://user-images.githubusercontent.com/65389500/127987547-a3d1e1a6-c886-4cd8-be57-6d4cced46115.png)

**Comment by Clansty** [comment]
在部分系统上可以，但是现在大部分的 Linux 桌面环境并不支持

**Comment by Jamie-obj** [comment]
> 在部分系统上可以，但是现在大部分的 Linux 桌面环境并不支持

好吧~

**Comment by lixiang810** [comment]
> 在部分系统上可以

（指我的 Archlinux KDE

**Comment by Clansty** [comment]
为啥我的 kde 就不行，左键也是菜单。是插件嘛

**Comment by lixiang810** [comment]
> 
> 
> 为啥我的 kde 就不行，左键也是菜单。是插件嘛

希腊奶，我没有特别的操作
