### ISSUE TITLE
Icalingua-2.1.3.AppImage 运行报错

### ISSUE THREAD

**Issue by pengdaCN** [Clansty/Icalingua#97]
使用普通用户运行
/tmp/.mount_IcalinyaWSRP/AppRun:行43: /tmp/.mount_IcalinyaWSRP/electron-qq: 权限不够

使用sudo 运行后
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
/tmp/.mount_IcalinQc2V0I/AppRun:行43: /tmp/.mount_IcalinQc2V0I/electron-qq: 权限不够

/opt/AppImage

**Comment by sukanka** [comment]
我也试了下,确实有这个问题,试试 2.1.4 https://github.com/Clansty/Icalingua/actions/runs/1094472567

**Comment by pengdaCN** [comment]
> 我也试了下,确实有这个问题,试试 2.1.4 https://github.com/Clansty/Icalingua/actions/runs/1094472567

嗯，用2.1.4 没有那个问题，已经可以顺利登录，感谢

**Comment by Clansty** [comment]
那个 2.1.3 版本有权限设置上的问题，已经修改了

另外请不要以 Root 身份运行 Icalingua
