### ISSUE TITLE
2.1.4 重新加载后界面数据显示有问题

### ISSUE THREAD

**Issue by kands-code** [Clansty/Icalingua#99]
版本为2.1.4，数据存储选定的是postgresql，登录时无问题，但选择重新加载后就会变成这个样子

![图片](https://user-images.githubusercontent.com/59006329/128114349-4be550da-d087-42b1-ac57-cdad72c01028.png)

连QQ号也变成了0，正常的应该是这样

![图片](https://user-images.githubusercontent.com/59006329/128114562-4a46ea1f-3505-467c-b06c-f02e5989d8ec.png)

**Comment by Clansty** [comment]
@kands-code 重新加载已经坏了

**Comment by kands-code** [comment]
az

**Comment by sukanka** [comment]
2.1.4 图标也有问题，Desktop文件里面写的是electron-qq.png,但是那个png现在已经叫Icalingua了。另外，手动改了这个问题，启动的时候dock还是显示electron的图标

**Comment by Jamie-obj** [comment]
> @kands-code 重新加载已经坏了

还有一个问题是在eqq上查看消息后，手机QQ上的消息小红点并不会消失

**Comment by Clansty** [comment]
@Jamie-obj 这个没法实现

**Comment by Jamie-obj** [comment]
> @Jamie-obj 这个没法实现

还有一个问题是，每次打开图片都是最大化窗口，不能修改成类似于qq那种的小窗口打开图片吗?
